Modules/Staff/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/staffs', 'StaffController@index')->name('staffs');

Route::resource('staffs', 'StaffController');

Route::get('/staffs/create', 'StaffController@create')->name('staffs.create');

Route::prefix('/')->group(function() {
    Route::get('/staffs', 'StaffController@index')->name('staffs');
  });

Modules/Staff/Entities/Staffs.php
<?php

namespace Modules\Staff\Entities;

use Illuminate\Database\Eloquent\Model;
use Modules\Staff\Entities\State;

class Staffs extends Model
{
    protected $fillable = [
        'fname',
        'lname',
        'position',
        'email',
        'gender',
        'department',
        'phone',
        'address',
        'salary',
        'from',
        'to',
        'dob'
    ];
    public function state()
    {
        return $this->belongsTo(State::class, 'state_id');
    }
}

Modules/Staff/Http/Controllers/StaffController.php
<?php

namespace Modules\Staff\Http\Controllers;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Staff\Entities\Staffs;

class StaffController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return Renderable
     */
    public function index()
    {
        $staffs = Staffs::all();
        return view('staff::index', compact('staffs'));
    }

    /**
     * Show the form for creating a new resource.
     * @return Renderable
     */
    public function create()
    {
        return view('staff::staffs.create');
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Renderable
     */
    public function store(Request $request)
    {
        $request->validate([
            'fname' => 'required',
            'lname' => 'required',
            'position' => 'required',
            'email' => 'required',
            'department' => 'required'
        ]);

        $staff = new Staffs([
            'fname' => $request->get('fname'),
            'lname' => $request->get('lname'),
            'position' => $request->get('position'),
            'email' => $request->get('email'),
            'gender' => $request->get('gender'),
            'department' => $request->get('department'),
            'phone' => $request->get('phone'),
            'address' => $request->get('address'),
            'salary' => $request->get('salary'),
            'from' => $request->get('from'),
            'to' => $request->get('to'),
            'dob' => $request->get('dob')
        ]);
        $staff -> save();
        return redirect('/staffs')->with('success', 'New Saff created!');
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function show($id)
    {
        return view('staff::show');
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function edit($id)
    {
        $staffs = Staffs::find($id);

        return view('staff::staffs.edit', compact('staffs'));
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Renderable
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'fname' => 'required',
            'lname' => 'required',
            'position' => 'required',
            'email' => 'required'
        ]);

        $staff = Staffs::find($id);

        $staff -> fname = $request->get('fname');
        $staff -> lname = $request->get('lname');
        $staff -> position = $request->get('position');
        $staff -> email = $request->get('email');
        $staff -> gender = $request->get('gender');
        $staff -> department = $request->get('department');
        $staff -> phone = $request->get('phone');
        $staff -> address = $request->get('address');
        $staff -> salary = $request->get('salary');
        $staff -> from = $request->get('from');
        $staff -> to = $request->get('to');
        $staff -> dob = $request->get('dob');
        $staff -> save();

        return redirect ('/staffs')-> with ('success', 'Staff details updated!');
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Renderable
     */
    public function destroy($id)
    {
        $staff = Staffs::find($id);
        $staff->delete();

        return redirect('/staffs')->with('success', 'Staff details deleted!');
    }
}

Modules/Staff/Resources/views/index.blade.php
@extends('layouts.app')

@section('content')
<style>
  .alert-fixed {
    position:fixed; 
    z-index:9999;
    right: 10vw;
}
</style>

<div class="container">
    <div class="row justify-content-center">
        <div class="row">
        <div class="col-sm-12">

  @if(session()->get('success'))
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script>
    $(document).ready(function() {
      $(".alert").fadeTo(5000, 500).slideUp(500, function() {
        $(".alert").slideUp(500);
      });
    });
  </script>
    <div class="alert alert-fixed alert-success">
      <button type="button" class="close" data-dismiss="alert"> &nbsp; &times;</button>
      {{ session()->get('success') }}  
    </div>
  @endif
</div>
        <div class="col-sm-12">
        
    <h1 class="display-3">Staffs <a href="{{ route('staffs.create') }}"><button type="submit" class="btn btn-primary">Add Staff</button></a></h1>    
    
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Name</td>
          <td>Gender</td>
          <td>Department</td>
          <td>Position</td>
          <td>Email</td>
          <td>Phone</td>
          <td>Address</td>
          <td>Salary</td>
          <td>From</td>
          <td>To</td>
          <td>DOB</td>
          <td colspan = 2>Actions</td>
        </tr>
    </thead>
    <tbody>
        @foreach($staffs as $staff)
        <tr>
            <td>{{$staff->id}}</td>
            <td>{{$staff->fname}} {{$staff->lname}}</td>
            <td>{{$staff->gender}}</td>
            <td>{{$staff->department}}</td>
            <td>{{$staff->position}}</td>
            <td>{{$staff->email}}</td>
            <td>{{$staff->phone}}</td>
            <td>{{$staff->address}}</td>
            <td>{{$staff->salary}}</td>
            <td>{{$staff->from}}</td>
            <td>{{$staff->to}}</td>
            <td>{{$staff->dob}}</td>
            <td>
                <a href="{{ route('staffs.edit',$staff->id)}}" class="btn btn-outline-primary">Edit</a>
            </td>
            <td>
                <form action="{{ route('staffs.destroy', $staff->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-outline-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
        </div>
    </div>
</div>
@endsection

Modules/Staff/Resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Module Staff</title>

       {{-- Laravel Mix - CSS File --}}
       {{-- <link rel="stylesheet" href="{{ mix('css/staff.css') }}"> --}}

    </head>
    <body>
        @yield('content')

        {{-- Laravel Mix - JS File --}}
        {{-- <script src="{{ mix('js/staff.js') }}"></script> --}}
    </body>
</html>

Modules/Staff/Resources/views/staffs/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="display-3">New Staff</h1>
                <div>
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div><br />
                    @endif
                    <form method="post" action="{{ route('staffs.store') }}">
                        @csrf
                        <div class="form-row">
                            <div class="col">    
                                <label for="fname">First Name:</label>
                                <input type="text" class="form-control" name="fname"/>
                            </div>
                            <div class="col">
                                <label for="lname">Last Name:</label>
                                <input type="text" class="form-control" name="lname"/>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="col">
                                <label for="email">Email:</label>
                                <input type="text" class="form-control" name="email" />
                            </div>
                            <div class="col">
                                <label for="phone">Phone:</label>
                                <input type="text" class="form-control" name="phone" />
                            </div>   
                        </div>

                        <div class="form-row">
                            <div class="col">
                                <label for="gender">Gender:</label>
                                <select class="form-control" name="gender" >
                                    <option value="Male">Male</option>
                                    <option value="Female">Female</option>
                                    <option value="N/A">N/A</option>
                                </select>
                            </div>
                            <div class="col">
                                <label for="department">Department:</label>
                                <select class="form-control" name="department" >
                                    <option value="Marketing">Marketing</option>
                                    <option value="Software">Software</option>
                                    <option value="Networking">Networking</option>
                                </select>
                            </div>
                            <div class="col">
                                <label for="position">Position:</label>
                                <input type="text" class="form-control" name="position" />
                            </div>
                        </div>

                         
                        <div class="form-group">
                            <label for="address">Address:</label>
                            <input type="text" class="form-control" name="address"/>
                        </div>    
                        <div class="form-row">
                            <div class="col">
                                <label for="salary">Salary:</label>
                                <input type="text" class="form-control" name="salary" />
                            </div>
                            <div class="col">
                                <label for="from">From:</label>
                                <input type="month" class="form-control" name="from" />
                            </div>     
                            <div class="col">
                                <label for="to">To:</label>
                                <input type="month" class="form-control" name="to" />
                            </div>
                            <div class="col">
                                <label for="dob">DOB:</label>
                                <input type="date" class="form-control" name="dob" />
                            </div>
                        </div><br />                        
                        <button type="submit" class="btn btn-primary">Add Staff</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

Modules/Staff/Resources/views/staffs/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="display-3">Update Staff</h1>
                <div>
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    <br /> 
                    @endif
                    <form method="post" action="{{ route('staffs.update', $staffs->id) }}">
                        @method('PATCH') 
                        @csrf

                        <div class="form-row">
                            <div class="col">    
                                <label for="fname">First Name:</label>
                                <input type="text" class="form-control" name="fname" value={{ $staffs->fname }} />
                            </div>
                            <div class="col">
                                <label for="lname">Last Name:</label>
                                <input type="text" class="form-control" name="lname" value={{ $staffs->lname }} />
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="col">
                                <label for="email">Email:</label>
                                <input type="text" class="form-control" name="email" value={{ $staffs->email }} />
                            </div>
                            <div class="col">
                                <label for="phone">Phone:</label>
                                <input type="text" class="form-control" name="phone" value={{ $staffs->phone }} />
                            </div>   
                        </div>

                        <div class="form-row">
                            <div class="col">
                                <label for="gender">Gender:</label>
                                <select class="form-control" name="gender">
                                    @if($staffs->gender == 'Male')
                                        <option value="Male" selected>Male</option>
                                        <option value="Female">Female</option>
                                        <option value="N/A">N/A</option>
                                    @elseif($staffs->gender == 'Female')
                                        <option value="Male">Male</option>
                                        <option value="Female" selected>Female</option>
                                        <option value="N/A">N/A</option>
                                    @elseif($staffs->gender == 'N/A')
                                        <option value="Male">Male</option>
                                        <option value="Female">Female</option>
                                        <option value="N/A" selected>N/A</option>
                                    @endif
                                </select>
                            </div>
                            <div class="col">
                                <label for="department">Department:</label>

                                <select class="form-control" name="department">
                                    @if($staffs->department == 'Marketing')
                                        <option value="Marketing" selected>Marketing</option>
                                        <option value="Software">Software</option>
                                        <option value="Networking">Networking</option>
                                    @elseif($staffs->department == 'Software')
                                        <option value="Marketing">Marketing</option>
                                        <option value="Software" selected>Software</option>
                                        <option value="Networking">Networking</option>
                                    @elseif($staffs->department == 'Networking')
                                        <option value="Marketing">Marketing</option>
                                        <option value="Software">Software</option>
                                        <option value="Networking" selected>Networking</option>
                                    @else
                                        <option value="Marketing" selected>Marketing</option>
                                        <option value="Software">Software</option>
                                        <option value="Networking">Networking</option>
                                    @endif
                                </select>
                            </div>
                            <div class="col">
                                <label for="position">Position:</label>
                                <input type="text" class="form-control" name="position" value={{ $staffs->position }} />
                            </div>
                        </div>

                         
                        <div class="form-group">
                            <label for="address">Address:</label>
                            <input type="text" class="form-control" name="address" value={{ $staffs->address }} />
                        </div>    
                        <div class="form-row">
                            <div class="col">
                                <label for="salary">Salary:</label>
                                <input type="text" class="form-control" name="salary" value={{ $staffs->salary }} />
                            </div>
                            <div class="col">
                                <label for="from">From:</label>
                                <input type="text" class="form-control" name="from" value={{ $staffs->from }} />
                            </div>     
                            <div class="col">
                                <label for="to">To:</label>
                                <input type="text" class="form-control" name="to" value={{ $staffs->to }} />
                            </div>
                            <div class="col">
                                <label for="dob">DOB:</label>
                                <input type="text" class="form-control" name="dob" value={{ $staffs->dob }} />
                            </div>
                        </div><br />                        
                        <button type="submit" class="btn btn-primary">Update Staff</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection